Drop Puppet 5 since its almost EOL
voxpupuli/puppet-borg pull request #82
Opened 2020-11-17 11:40 UTC by bastelfreak

Puppet 5 is EOL in a few days. Based on that I assume it's safe to
already drop it. It also allows us to test the migration to GitHub Action.

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2020-11-17 11:46 UTC, ekohl commented
This still tests the old versions. I'd like to finish https://github.com/voxpupuli/modulesync_config/pull/683 and then this will be sufficient.

2020-11-17 11:55 UTC, ekohl commented
This still tests the old versions. I'd like to finish https://github.com/voxpupuli/modulesync_config/pull/683 and then this will be sufficient.

2020-11-27 13:09 UTC, ekohl requested changes
Needs a rebase now.

2020-11-27 13:43 UTC, ekohl approved these changes
Code wise it looks good to me. Still not sure if we should be so aggressive in dropping it.

2020-11-27 14:14 UTC, bastelfreak commented
yes. I agree we should wait with it

2021-06-15 13:54 UTC, closed without merging